version: '3'

services:
  app:
    build: ./docker/php/

    ports:
      - "5173:5173"
    volumes:
      - ./src:/app
    depends_on:
      - db
  nginx:
    build: ./docker/nginx/
    ports:
      - 81:80
    volumes:
      - ./src/:/app
    depends_on:
      - app
  db:
    build: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - mysql-volume:/var/lib/mysql
volumes:
  mysql-volume: